CREATE TABLE IF NOT EXISTS user_profiles (
    username TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS ref_asset_class (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ref_region (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS ref_sector (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS ref_price_source (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ref_instrument_type (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL
);


create table if not exists ref_currencies (
  code char(3) primary key,
  label text not null,      
  created_at timestamptz default now()
);


CREATE TABLE IF NOT EXISTS asset_static_data (
  isin VARCHAR(12) PRIMARY KEY,
  name TEXT NOT NULL,
  currency VARCHAR(3) REFERENCES ref_currencies(code),
  ticker TEXT,

  price_source TEXT REFERENCES ref_price_source(code),
  instrument_type TEXT REFERENCES ref_instrument_type(code),
  asset_class_code TEXT REFERENCES ref_asset_class(code),
  region_code TEXT REFERENCES ref_region(code),
  sector_code TEXT REFERENCES ref_sector(code),

  industry TEXT,
  country TEXT,
  
  closed_on DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);

ALTER TABLE asset_static_data 
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS updated_by TEXT;




CREATE TABLE IF NOT EXISTS ref_transaction_type (
    code TEXT PRIMARY KEY,
    label TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
    username TEXT NOT NULL,
    account_code TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (username, account_code)
);


CREATE TABLE IF NOT EXISTS transactions (
    username TEXT NOT NULL,
    id TEXT NOT NULL,
    account_code TEXT NOT NULL,
    isin VARCHAR(12),
    date DATE DEFAULT CURRENT_DATE,
    type_code TEXT,
    quantity NUMERIC(20, 8),
    settle_amount NUMERIC(20, 8),
    settle_currency VARCHAR(3),
    settle_fxrate NUMERIC(20, 10),
    amount_eur NUMERIC(20, 8),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    
    PRIMARY KEY (username, id),
    
    CONSTRAINT fk_ref_type
        FOREIGN KEY (type_code) REFERENCES ref_transaction_type(code)
        ON DELETE SET NULL,

    CONSTRAINT fk_transaction_ref_currency
        FOREIGN KEY (settle_currency) REFERENCES ref_currencies(code) 
        ON DELETE SET NULL,

    CONSTRAINT fk_transaction_isin
        FOREIGN KEY (isin) REFERENCES asset_static_data(isin)
        ON DELETE SET NULL,
    
    CONSTRAINT fk_accounts
        FOREIGN KEY (username, account_code) REFERENCES accounts(username, account_code)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_import_settings (
    username TEXT NOT NULL,
    account_code TEXT NOT NULL,
    mapping_config JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (username, account_code),
    
    -- Der Foreign Key sorgt für Ordnung:
    CONSTRAINT fk_user_account
        FOREIGN KEY (username, account_code) 
        REFERENCES accounts(username, account_code)
        ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS country_region_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country TEXT NOT NULL UNIQUE,
    region_code TEXT REFERENCES ref_region(code) ON UPDATE CASCADE ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);




-- Historical price data for assets
CREATE TABLE IF NOT EXISTS asset_prices (
    isin VARCHAR(12) NOT NULL REFERENCES asset_static_data(isin) ON DELETE CASCADE,
    price_date DATE NOT NULL,
    price_close NUMERIC(20, 6) NOT NULL,
    -- Composite primary key: ensures one price per asset per day
    PRIMARY KEY (isin, price_date)
);

-- Index for efficient time-series charting
CREATE INDEX idx_asset_prices_date ON asset_prices(price_date);



-- Historical foreign exchange rates relative to EUR
CREATE TABLE IF NOT EXISTS exchange_rates (
    currency_pair VARCHAR(6) NOT NULL, -- Format: 'EURUSD', 'EURCHF'
    rate_date DATE NOT NULL,
    exchange_rate NUMERIC(20, 10) NOT NULL,
    -- Primary key: ensures one rate per pair per day
    PRIMARY KEY (currency_pair, rate_date)
);

-- Index for fast conversion lookups
CREATE INDEX idx_exchange_rates_date ON exchange_rates(rate_date);




-- Daily snapshot of quantities per user, account, and asset
CREATE TABLE IF NOT EXISTS daily_holdings (
    username TEXT NOT NULL,
    account_code TEXT NOT NULL,
    isin VARCHAR(12) NOT NULL,
    holding_date DATE NOT NULL,
    quantity NUMERIC(20, 8) NOT NULL,
    
    -- Primary key: ensures unique record per day, account and asset
    PRIMARY KEY (username, account_code, isin, holding_date),
    
    -- Foreign Key to ensure the account exists for this user
    CONSTRAINT fk_daily_holdings_account
        FOREIGN KEY (username, account_code) 
        REFERENCES accounts(username, account_code) 
        ON DELETE CASCADE,
        
    -- Foreign Key to link to asset details
    CONSTRAINT fk_daily_holdings_isin
        FOREIGN KEY (isin) 
        REFERENCES asset_static_data(isin) 
        ON DELETE CASCADE
);

-- Index for faster filtering by user and date
CREATE INDEX idx_daily_holdings_lookup ON daily_holdings(username, holding_date);


