-- --- SCHEMA INITIALIZATION ---
CREATE SCHEMA IF NOT EXISTS shared;
CREATE SCHEMA IF NOT EXISTS public;

-- --- create user table first ---

-- Central User Table (Profile Data)
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE, -- Optional / Nullable
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE VIEW shared.users WITH (security_invoker = true) AS SELECT id, username FROM public.users;




-- --- SHARED SCHEMA TABLES (Global / Non-user specific) ---

CREATE TABLE IF NOT EXISTS shared.ref_asset_class (code TEXT PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shared.ref_region (code TEXT PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shared.ref_sector (code TEXT PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shared.ref_price_source (code TEXT PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shared.ref_instrument_type (code TEXT PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shared.ref_transaction_type (code TEXT PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS shared.ref_currencies (code CHAR(3) PRIMARY KEY, label TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());

CREATE OR REPLACE VIEW public.ref_transaction_type WITH (security_invoker = true) AS SELECT code, label FROM shared.ref_transaction_type;

CREATE TABLE IF NOT EXISTS shared.ref_transaction_logic (
    transaction_type_code TEXT PRIMARY KEY,
    quantity_sign SMALLINT, -- +1: abs(), -1: -abs(), 0: force NULL, NULL: as is
    amount_sign SMALLINT,   -- +1: abs(), -1: -abs(), 0: force NULL, NULL: as is
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_logic_transaction_type FOREIGN KEY (transaction_type_code) REFERENCES shared.ref_transaction_type(code) ON DELETE CASCADE
);



-- Global asset static data
CREATE TABLE IF NOT EXISTS shared.asset_static_data (
    isin VARCHAR(12) PRIMARY KEY,
    name TEXT NOT NULL,
    currency VARCHAR(3),
    ticker TEXT,
    price_source_code TEXT,
    instrument_type_code TEXT,
    asset_class_code TEXT,
    region_code TEXT,
    sector_code TEXT,
    industry TEXT,
    country TEXT,
    closed_on DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,

    CONSTRAINT fk_static_currency FOREIGN KEY (currency) REFERENCES shared.ref_currencies(code) ON DELETE SET NULL,
    CONSTRAINT fk_static_price_source FOREIGN KEY (price_source_code) REFERENCES shared.ref_price_source(code) ON DELETE SET NULL,
    CONSTRAINT fk_static_instrument_type FOREIGN KEY (instrument_type_code) REFERENCES shared.ref_instrument_type(code) ON DELETE SET NULL,
    CONSTRAINT fk_static_asset_class FOREIGN KEY (asset_class_code) REFERENCES shared.ref_asset_class(code) ON DELETE SET NULL,
    CONSTRAINT fk_static_region FOREIGN KEY (region_code) REFERENCES shared.ref_region(code) ON DELETE SET NULL,
    CONSTRAINT fk_static_sector FOREIGN KEY (sector_code) REFERENCES shared.ref_sector(code) ON DELETE SET NULL,
    CONSTRAINT fk_static_created_by FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL,
    CONSTRAINT fk_static_updated_by FOREIGN KEY (updated_by) REFERENCES public.users(id) ON DELETE SET NULL
);


CREATE OR REPLACE VIEW public.asset_static_data WITH (security_invoker = true) AS SELECT isin, name FROM shared.asset_static_data;

-- Mapping for countries to regions
CREATE TABLE IF NOT EXISTS shared.country_region_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country TEXT NOT NULL UNIQUE,
    region_code TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_country_map_region FOREIGN KEY (region_code) REFERENCES shared.ref_region(code) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Historical price data for assets
CREATE TABLE IF NOT EXISTS shared.asset_prices (
    isin VARCHAR(12) NOT NULL,
    price_date DATE NOT NULL,
    price_close NUMERIC(20, 6) NOT NULL,
    -- Composite primary key: ensures one price per asset per day
    PRIMARY KEY (isin, price_date),

    CONSTRAINT fk_prices_isin FOREIGN KEY (isin) REFERENCES shared.asset_static_data(isin) ON DELETE CASCADE
);
-- Index for efficient time-series charting
CREATE INDEX IF NOT EXISTS idx_asset_prices_isin_date ON shared.asset_prices (isin, price_date DESC);


-- Historical foreign exchange rates relative to EUR
CREATE TABLE IF NOT EXISTS shared.exchange_rates (
    currency VARCHAR(3) NOT NULL, -- Format for yfinance: 'EURUSD', 'EURCHF' etc.
    rate_date DATE NOT NULL,
    exchange_rate NUMERIC(20, 10) NOT NULL,
    -- Primary key: ensures one rate per pair per day
    PRIMARY KEY (currency, rate_date),

    CONSTRAINT fk_exchange_rates_ref_currency
        FOREIGN KEY (currency) REFERENCES shared.ref_currencies(code) 
        ON DELETE SET NULL
);
-- Index for fast conversion lookups
CREATE INDEX IF NOT EXISTS idx_exchange_rates_curr_date ON shared.exchange_rates (currency, rate_date DESC);


-- --- PUBLIC SCHEMA TABLES (User specific) ---

-- Separate Table for Sensitive Auth Data
CREATE TABLE IF NOT EXISTS public.user_secrets (
    user_id UUID PRIMARY KEY,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_secrets_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- User brokerage/bank accounts
CREATE TABLE IF NOT EXISTS public.accounts (
    user_id UUID NOT NULL,
    account_code TEXT NOT NULL,
    description TEXT,
    PRIMARY KEY (user_id, account_code),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- Investment transactions per user
CREATE TABLE IF NOT EXISTS public.transactions (
    user_id UUID NOT NULL,
    id TEXT NOT NULL,
    account_code TEXT NOT NULL,
    isin VARCHAR(12),
    date DATE DEFAULT CURRENT_DATE,
    transaction_type_code TEXT,
    quantity NUMERIC(20, 8),
    settle_amount NUMERIC(20, 8),
    settle_currency VARCHAR(3),
    settle_fxrate NUMERIC(20, 10),
    amount_eur NUMERIC(20, 8),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ,
    
    PRIMARY KEY (user_id, id),
    CONSTRAINT fk_transactions_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_ref_type FOREIGN KEY (transaction_type_code) REFERENCES shared.ref_transaction_type(code) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_ref_currency FOREIGN KEY (settle_currency) REFERENCES shared.ref_currencies(code) ON DELETE SET NULL,
    CONSTRAINT fk_transaction_isin FOREIGN KEY (isin) REFERENCES shared.asset_static_data(isin) ON DELETE SET NULL,
    CONSTRAINT fk_accounts FOREIGN KEY (user_id, account_code) REFERENCES public.accounts(user_id, account_code) ON DELETE CASCADE
);

-- User settings for data import
CREATE TABLE IF NOT EXISTS public.user_import_settings (
    user_id UUID NOT NULL,
    account_code TEXT NOT NULL,
    mapping_config JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, account_code),
    CONSTRAINT fk_user_import_account FOREIGN KEY (user_id, account_code) REFERENCES public.accounts(user_id, account_code) ON DELETE CASCADE
);

-- Daily snapshot of quantities per user, account, and asset
-- only increments the date if the holdings change
CREATE TABLE IF NOT EXISTS public.incremental_holdings (
    user_id UUID NOT NULL,
    account_code TEXT NOT NULL,
    holding_date DATE NOT NULL,
    isin VARCHAR(12) NOT NULL,
    quantity NUMERIC(20, 8) NOT NULL,
    PRIMARY KEY (user_id, account_code, holding_date, isin),
    CONSTRAINT fk_incremental_holdings_account FOREIGN KEY (user_id, account_code) REFERENCES public.accounts(user_id, account_code) ON DELETE CASCADE,
    CONSTRAINT fk_incremental_holdings_isin FOREIGN KEY (isin) REFERENCES shared.asset_static_data(isin) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_holdings_lookup ON public.incremental_holdings (user_id, account_code, isin, holding_date DESC);


-- view to create daily holdings by filling the gaps in incremental_holdings
CREATE OR REPLACE VIEW public.daily_holdings WITH (security_invoker = true) AS
WITH date_range AS (
    -- 1. Wir ermitteln den Startpunkt und das Ende der Zeitreihe
    SELECT 
        min(holding_date) as start_date, 
        CURRENT_DATE as end_date 
    FROM public.incremental_holdings
),
all_days AS (
    -- 2. Wir generieren jeden einzelnen Tag
    SELECT generate_series(start_date, end_date, '1 day'::interval)::date AS day
    FROM date_range
),
distinct_keys AS (
    -- 3. Wir brauchen alle Kombinationen aus User, Account und ISIN, die existieren
    SELECT DISTINCT user_id, account_code, isin 
    FROM public.incremental_holdings
)
-- 4. Wir verbinden die Tage mit den Keys und suchen den letzten Stand
SELECT 
    k.user_id,
    k.account_code,
    d.day AS holding_date,
    k.isin,
    h.quantity
FROM all_days d
CROSS JOIN distinct_keys k -- Erzeugt für jeden Tag eine Zeile pro Asset
LEFT JOIN LATERAL (
    -- Dieser Teil sucht für jeden Tag den "aktuellsten" Eintrag in der echten Tabelle
    SELECT ih.quantity
    FROM public.incremental_holdings ih
    WHERE ih.user_id = k.user_id
      AND ih.account_code = k.account_code
      AND ih.isin = k.isin
      AND ih.holding_date <= d.day
    ORDER BY ih.holding_date DESC
    LIMIT 1
) h ON TRUE
WHERE h.quantity IS NOT NULL; -- Verhindert Zeilen für Assets vor ihrem ersten Kauf






-- ==========================================================
-- 3. ENABLING ROW LEVEL SECURITY (RLS)
-- ==========================================================
-- This enables RLS for all tables in the shared schema
DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'shared' AND table_type = 'BASE TABLE') 
    LOOP
        EXECUTE format('ALTER TABLE shared.%I ENABLE ROW LEVEL SECURITY', t);
    END LOOP;
END $$;

-- ==========================================================
-- 4. POLICIES (SHARED SCHEMA)
-- ==========================================================

-- A: READ ACCESS FOR EVERYONE (anon & authenticated)
-- We use a loop to apply the "Public Read" policy to all shared tables
DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'shared' AND table_type = 'BASE TABLE') 
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Public Read Access" ON shared.%I', t);
        EXECUTE format('CREATE POLICY "Public Read Access" ON shared.%I FOR SELECT USING (true)', t);
    END LOOP;
END $$;

-- B: WRITE ACCESS (Only authenticated users or system)
-- For shared data, we typically don't want 'anon' to insert data.
-- If you want logged-in users to propose new assets:
DROP POLICY IF EXISTS "Authenticated Insert Access" ON shared.asset_static_data;
CREATE POLICY "Authenticated Insert Access" ON shared.asset_static_data 
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- C: UPDATE ACCESS (Only authenticated users or system)
DROP POLICY IF EXISTS "Authenticated Update Access" ON shared.asset_static_data;
CREATE POLICY "Authenticated Update Access" ON shared.asset_static_data 
FOR UPDATE TO authenticated USING (true) WITH CHECK (true);


-- ==========================================================
-- 5. PERMISSIONS (GRANTS)
-- ==========================================================
-- Grant schema usage

GRANT USAGE ON SCHEMA shared TO anon, authenticated;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

GRANT SELECT ON ALL TABLES IN SCHEMA shared TO anon, authenticated;
GRANT INSERT ON shared.asset_static_data TO authenticated;
GRANT UPDATE ON shared.asset_static_data TO authenticated;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT UPDATE ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
